# Generated by Django 5.2.1 on 2025-05-15 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('input', models.JSONField()),
                ('output', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
